version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: file-sharing
    environment:
      POSTGRES_USER: jonix
      POSTGRES_PASSWORD: jonix
      POSTGRES_DB: jonix
    ports:
      - "5433:5432"
    volumes:
      - file-sharing:/var/lib/postgresql/data

volumes:
  file-sharing: 